// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	User
	Session
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	UpdateNameRequest
	UpdateNameResponse
	UpdatePasswordRequest
	UpdatePasswordResponse
	SearchRequest
	SearchResponse
	ReadSessionRequest
	ReadSessionResponse
	LoginRequest
	LoginResponse
	LogoutRequest
	LogoutResponse
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type User struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Created   int64  `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	Updated   int64  `protobuf:"varint,5,opt,name=updated" json:"updated,omitempty"`
	AppId     string `protobuf:"bytes,6,opt,name=appId" json:"appId,omitempty"`
	AppSecret string `protobuf:"bytes,7,opt,name=appSecret" json:"appSecret,omitempty"`
	Platform  string `protobuf:"bytes,8,opt,name=platform" json:"platform,omitempty"`
	Password  string `protobuf:"bytes,9,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Session struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Created  int64  `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	Expires  int64  `protobuf:"varint,4,opt,name=expires" json:"expires,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateRequest struct {
	User     *User  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ReadResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type UpdateNameRequest struct {
	Email       string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Oldusername string `protobuf:"bytes,2,opt,name=oldusername" json:"oldusername,omitempty"`
	Username    string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
}

func (m *UpdateNameRequest) Reset()                    { *m = UpdateNameRequest{} }
func (m *UpdateNameRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateNameRequest) ProtoMessage()               {}
func (*UpdateNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type UpdateNameResponse struct {
}

func (m *UpdateNameResponse) Reset()                    { *m = UpdateNameResponse{} }
func (m *UpdateNameResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateNameResponse) ProtoMessage()               {}
func (*UpdateNameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type UpdatePasswordRequest struct {
	UserId          string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	OldPassword     string `protobuf:"bytes,2,opt,name=oldPassword" json:"oldPassword,omitempty"`
	NewPassword     string `protobuf:"bytes,3,opt,name=newPassword" json:"newPassword,omitempty"`
	ConfirmPassword string `protobuf:"bytes,4,opt,name=confirmPassword" json:"confirmPassword,omitempty"`
}

func (m *UpdatePasswordRequest) Reset()                    { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()               {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type UpdatePasswordResponse struct {
}

func (m *UpdatePasswordResponse) Reset()                    { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()               {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type SearchRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset   int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type SearchResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type ReadSessionRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
}

func (m *ReadSessionRequest) Reset()                    { *m = ReadSessionRequest{} }
func (m *ReadSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadSessionRequest) ProtoMessage()               {}
func (*ReadSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type ReadSessionResponse struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
}

func (m *ReadSessionResponse) Reset()                    { *m = ReadSessionResponse{} }
func (m *ReadSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadSessionResponse) ProtoMessage()               {}
func (*ReadSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ReadSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type LoginResponse struct {
	Session *Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *LoginResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type LogoutRequest struct {
	SessionId string `protobuf:"bytes,1,opt,name=sessionId" json:"sessionId,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type LogoutResponse struct {
}

func (m *LogoutResponse) Reset()                    { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()               {}
func (*LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Session)(nil), "Session")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*UpdateNameRequest)(nil), "UpdateNameRequest")
	proto.RegisterType((*UpdateNameResponse)(nil), "UpdateNameResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "UpdatePasswordResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*ReadSessionRequest)(nil), "ReadSessionRequest")
	proto.RegisterType((*ReadSessionResponse)(nil), "ReadSessionResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "LogoutResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Account service

type AccountClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	UpdateName(ctx context.Context, in *UpdateNameRequest, opts ...client.CallOption) (*UpdateNameResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...client.CallOption) (*UpdatePasswordResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...client.CallOption) (*LogoutResponse, error)
	ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...client.CallOption) (*ReadSessionResponse, error)
}

type accountClient struct {
	c           client.Client
	serviceName string
}

func NewAccountClient(serviceName string, c client.Client) AccountClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "account"
	}
	return &accountClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateName(ctx context.Context, in *UpdateNameRequest, opts ...client.CallOption) (*UpdateNameResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.UpdateName", in)
	out := new(UpdateNameResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...client.CallOption) (*UpdatePasswordResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.UpdatePassword", in)
	out := new(UpdatePasswordResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Logout(ctx context.Context, in *LogoutRequest, opts ...client.CallOption) (*LogoutResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.Logout", in)
	out := new(LogoutResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ReadSession(ctx context.Context, in *ReadSessionRequest, opts ...client.CallOption) (*ReadSessionResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Account.ReadSession", in)
	out := new(ReadSessionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	UpdateName(context.Context, *UpdateNameRequest, *UpdateNameResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	UpdatePassword(context.Context, *UpdatePasswordRequest, *UpdatePasswordResponse) error
	Login(context.Context, *LoginRequest, *LoginResponse) error
	Logout(context.Context, *LogoutRequest, *LogoutResponse) error
	ReadSession(context.Context, *ReadSessionRequest, *ReadSessionResponse) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler) {
	s.Handle(s.NewHandler(&Account{hdlr}))
}

type Account struct {
	AccountHandler
}

func (h *Account) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.AccountHandler.Create(ctx, in, out)
}

func (h *Account) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.AccountHandler.Read(ctx, in, out)
}

func (h *Account) UpdateName(ctx context.Context, in *UpdateNameRequest, out *UpdateNameResponse) error {
	return h.AccountHandler.UpdateName(ctx, in, out)
}

func (h *Account) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.AccountHandler.Update(ctx, in, out)
}

func (h *Account) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.AccountHandler.Delete(ctx, in, out)
}

func (h *Account) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.AccountHandler.Search(ctx, in, out)
}

func (h *Account) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, out *UpdatePasswordResponse) error {
	return h.AccountHandler.UpdatePassword(ctx, in, out)
}

func (h *Account) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.AccountHandler.Login(ctx, in, out)
}

func (h *Account) Logout(ctx context.Context, in *LogoutRequest, out *LogoutResponse) error {
	return h.AccountHandler.Logout(ctx, in, out)
}

func (h *Account) ReadSession(ctx context.Context, in *ReadSessionRequest, out *ReadSessionResponse) error {
	return h.AccountHandler.ReadSession(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x4e, 0xe2, 0x7c, 0xb4, 0xd3, 0xda, 0x7d, 0xdf, 0x6d, 0x29, 0xc6, 0x80, 0xa8, 0x56, 0x42,
	0x2a, 0xa0, 0xee, 0xa1, 0x3d, 0x20, 0xb8, 0xa1, 0x22, 0xa4, 0x4a, 0x08, 0x55, 0xa9, 0x7a, 0xe3,
	0x62, 0xe2, 0x4d, 0xb1, 0x94, 0x78, 0x8d, 0xd7, 0x51, 0xf9, 0x33, 0xfc, 0x3f, 0xfe, 0x00, 0x77,
	0xf6, 0xd3, 0xde, 0x75, 0x13, 0x41, 0xb9, 0x79, 0x66, 0x9e, 0xdd, 0x79, 0x76, 0x66, 0x9e, 0x31,
	0x84, 0xe9, 0x6c, 0xc6, 0x56, 0x45, 0x4d, 0xca, 0x8a, 0xd5, 0x0c, 0xff, 0xec, 0xc3, 0xf0, 0x9a,
	0xd3, 0x0a, 0x45, 0x30, 0xc8, 0xb3, 0xb8, 0x7f, 0xd4, 0x3f, 0xde, 0x9e, 0x8a, 0x2f, 0x94, 0xc0,
	0xd6, 0x4a, 0xf8, 0x8b, 0x74, 0x49, 0xe3, 0x81, 0xf2, 0x36, 0x36, 0x3a, 0x80, 0x11, 0x5d, 0xa6,
	0xf9, 0x22, 0x0e, 0x54, 0x40, 0x1b, 0x28, 0x86, 0xc9, 0xac, 0xa2, 0x69, 0x4d, 0xb3, 0x78, 0x28,
	0xfc, 0xc1, 0xd4, 0x9a, 0x32, 0xb2, 0x2a, 0x33, 0x15, 0x19, 0xe9, 0x88, 0x31, 0xe5, 0x4d, 0x69,
	0x59, 0x5e, 0x64, 0xf1, 0x58, 0xdf, 0xa4, 0x0c, 0xf4, 0x04, 0xb6, 0xc5, 0xc7, 0x15, 0x15, 0xe7,
	0xeb, 0x78, 0xa2, 0x22, 0xad, 0x43, 0x32, 0x2b, 0x17, 0x69, 0x3d, 0x67, 0xd5, 0x32, 0xde, 0xd2,
	0xcc, 0xac, 0xad, 0x62, 0x29, 0xe7, 0xb7, 0xac, 0xca, 0xe2, 0x6d, 0x13, 0x33, 0x36, 0xce, 0x61,
	0x72, 0x45, 0x39, 0xcf, 0x59, 0x71, 0xaf, 0xc7, 0x3a, 0xcf, 0x0a, 0xee, 0x3c, 0x8b, 0x7e, 0x2f,
	0xf3, 0x8a, 0x72, 0xfb, 0x60, 0x63, 0xe2, 0x0f, 0x10, 0x9e, 0x2b, 0xd0, 0x94, 0x7e, 0x5b, 0x51,
	0x5e, 0xa3, 0x47, 0x30, 0x94, 0x17, 0xaa, 0x94, 0x3b, 0xa7, 0x23, 0x22, 0x4b, 0x3e, 0x55, 0x2e,
	0x8f, 0xf2, 0xa0, 0x43, 0xf9, 0x08, 0x22, 0x7b, 0x0f, 0x2f, 0x59, 0xc1, 0x69, 0x97, 0x39, 0x7e,
	0x06, 0xe1, 0x7b, 0xba, 0xa0, 0x6d, 0xa6, 0x2e, 0xe0, 0x3f, 0x88, 0x2c, 0x40, 0x5f, 0x81, 0x9f,
	0xc2, 0xce, 0x94, 0xa6, 0xd9, 0xa6, 0x03, 0x2f, 0x60, 0x57, 0x87, 0x4d, 0xc6, 0xcd, 0xd4, 0xf1,
	0x4b, 0x08, 0xaf, 0x55, 0x23, 0xff, 0xfc, 0x4c, 0xc9, 0xc3, 0x62, 0x0d, 0x8f, 0x1b, 0xf8, 0x5f,
	0x7b, 0x3e, 0x89, 0x32, 0xdb, 0x1b, 0x9a, 0xd1, 0xea, 0xbb, 0xa3, 0x75, 0x04, 0x3b, 0x6c, 0x91,
	0x75, 0x5a, 0xe4, 0xba, 0xbc, 0x0e, 0x06, 0x7e, 0x07, 0xf1, 0x01, 0x20, 0x37, 0x91, 0x49, 0xff,
	0xa3, 0x0f, 0x0f, 0xb4, 0xfb, 0xd2, 0x94, 0xdb, 0x72, 0x38, 0x84, 0xb1, 0x3c, 0x7b, 0x61, 0xab,
	0x62, 0x2c, 0xc3, 0xe2, 0xd2, 0x6f, 0x96, 0xeb, 0x92, 0x88, 0x82, 0xde, 0x36, 0x08, 0x4d, 0xc4,
	0x75, 0xa1, 0x63, 0xd8, 0x9b, 0xb1, 0x62, 0x9e, 0x57, 0xcb, 0x06, 0x35, 0x54, 0xa8, 0xae, 0x1b,
	0xc7, 0x70, 0xd8, 0xa5, 0x67, 0x98, 0x33, 0x08, 0xaf, 0x68, 0x5a, 0xcd, 0xbe, 0x5a, 0xc2, 0xee,
	0xe3, 0xfb, 0x9b, 0xb4, 0x3a, 0x70, 0x0b, 0x2a, 0xbc, 0x8b, 0x7c, 0x99, 0xd7, 0x66, 0xa4, 0xb5,
	0x21, 0x1f, 0xce, 0xe6, 0x73, 0x2e, 0x44, 0xa7, 0xe7, 0xd9, 0x58, 0xf8, 0x04, 0x22, 0x9b, 0xd0,
	0x0c, 0xc5, 0x63, 0x18, 0xc9, 0x0c, 0x5c, 0xa4, 0x0b, 0xda, 0x4e, 0x6b, 0x1f, 0x3e, 0x05, 0x24,
	0x27, 0xc8, 0x88, 0xcd, 0x92, 0x14, 0xa2, 0xe6, 0xda, 0xd3, 0x14, 0xb6, 0x75, 0xe0, 0x37, 0xb0,
	0xef, 0x9d, 0x31, 0x79, 0x30, 0x4c, 0x0c, 0xc6, 0xcc, 0xd4, 0x16, 0xb1, 0x10, 0x1b, 0xc0, 0x9f,
	0x61, 0xf7, 0x23, 0xbb, 0xc9, 0x8b, 0x7f, 0xaf, 0x86, 0x2b, 0xc1, 0xa0, 0x23, 0xc1, 0x33, 0x08,
	0xcd, 0xed, 0xf7, 0xa0, 0x74, 0xa2, 0x0e, 0xb1, 0x55, 0xfd, 0x77, 0x8f, 0x17, 0xda, 0xb0, 0x70,
	0x9d, 0xe4, 0xf4, 0x57, 0x00, 0x93, 0x77, 0x7a, 0x51, 0xa3, 0x57, 0x30, 0xd6, 0x4b, 0x00, 0x45,
	0xc4, 0xdb, 0x2a, 0xc9, 0x1e, 0xf1, 0xb7, 0x03, 0xee, 0xa1, 0xe7, 0x30, 0x94, 0x75, 0x44, 0xbb,
	0xc4, 0xd1, 0x78, 0x12, 0x12, 0x57, 0xd2, 0x02, 0xf6, 0x1a, 0xa0, 0x95, 0x04, 0x42, 0xe4, 0x8e,
	0x10, 0x93, 0x7d, 0xb2, 0x46, 0x33, 0x3d, 0x49, 0x46, 0xfb, 0x05, 0x19, 0x4f, 0xfb, 0x82, 0x4c,
	0x47, 0xdf, 0x0a, 0xac, 0x77, 0x8f, 0x00, 0x7b, 0x5b, 0x4a, 0x80, 0x3b, 0x4b, 0x49, 0x81, 0xf5,
	0x90, 0x09, 0xb0, 0x37, 0xde, 0x02, 0xec, 0x4f, 0x9f, 0x00, 0x9f, 0xdb, 0x6d, 0xd2, 0x08, 0xeb,
	0x90, 0xac, 0x15, 0x73, 0xf2, 0x90, 0x6c, 0x50, 0x51, 0x4f, 0x68, 0x71, 0xa4, 0x5a, 0x8b, 0x42,
	0xe2, 0x0e, 0x50, 0x12, 0x11, 0xaf, 0xe3, 0x9a, 0x9b, 0x6e, 0x10, 0x52, 0xb1, 0xb6, 0xb1, 0x82,
	0x9b, 0xdf, 0x39, 0x01, 0x7e, 0xab, 0xf7, 0xab, 0xfd, 0xd7, 0xec, 0x93, 0xbb, 0x62, 0x48, 0x0e,
	0xc8, 0x9a, 0x69, 0xc7, 0xbd, 0x2f, 0x63, 0xf5, 0x57, 0x3e, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xb2, 0x33, 0x4e, 0xf9, 0xa6, 0x07, 0x00, 0x00,
}
